"""Section, hold, disposition, and match-reference labels shared across the matching package."""

from __future__ import annotations




REFERENCE_HOLD_SECTION = "11 Review Hold QuickBooks"


HOLD_PO_ALREADY_REPRESENTED = "REVIEW_HOLD_PO_ALREADY_REPRESENTED"


HOLD_AMOUNT_VARIANCE = "REVIEW_HOLD_AMOUNT_VARIANCE"


HOLD_EXACT_CANDIDATE_NOT_UNIQUE = "REVIEW_HOLD_EXACT_CANDIDATE_NOT_UNIQUE"


HOLD_MULTIPLE_CANDIDATES = "REVIEW_HOLD_MULTIPLE_CANDIDATES"


HOLD_PO_REUSE = "REVIEW_HOLD_PO_REUSE"


HOLD_TYPO_CANDIDATES = "REVIEW_HOLD_TYPO_CANDIDATES"


HOLD_HISTORICAL_CLEARANCE = "REVIEW_HOLD_HISTORICAL_CLEARANCE"


HOLD_POTENTIAL_DUPLICATE = "REVIEW_HOLD_POTENTIAL_DUPLICATE"


HOLD_INVALID_AMOUNT = "REVIEW_HOLD_INVALID_AMOUNT"


HOLD_CANDIDATE_INVALID_AMOUNT = "REVIEW_HOLD_CANDIDATE_INVALID_AMOUNT"


HOLD_CONFLICTING_LINKS = "REVIEW_HOLD_CONFLICTING_LINKS"


HOLD_WEAK_REFERENCE = "REVIEW_HOLD_WEAK_REFERENCE"


REFERENCE_HOLD_COLUMNS = [
    "Hold ID", "Reason Code", "Classification", "Confidence",
    "QuickBooks Row ID", "QuickBooks Row Index", "Normalized PO", "Normalized Invoice",
    "QuickBooks Amount", "Infinium Amount", "Amount Difference",
    "Related Match Ref.", "Related QuickBooks Row IDs", "Related Infinium Row IDs",
    "Accrual Treatment", "Posting Disposition", "Explanation",
    "Manual Decision", "Reviewed By", "Review Timestamp", "Review Rationale",
    "Evidence Finding", "Candidate Evidence",
]


DISPOSITION_MATCHED = "MATCHED"


DISPOSITION_DUPLICATE_EXCLUDED = "EXACT_QBO_DUPLICATE_EXCLUDED"


DISPOSITION_REVIEW_HOLD = "REVIEW_HOLD"


DISPOSITION_TRUE_UNMATCHED = "TRUE_UNMATCHED"


FINAL_DISPOSITIONS = (
    DISPOSITION_MATCHED,
    DISPOSITION_DUPLICATE_EXCLUDED,
    DISPOSITION_REVIEW_HOLD,
    DISPOSITION_TRUE_UNMATCHED,
)


QB_DISPOSITION_COLUMNS = [
    "QBO Row ID", "Normalized PO", "Normalized Invoice", "Amount",
    "Final Disposition", "Reason Code", "Final Reason",
    "Match Ref.", "Aggregate Group ID", "Duplicate Group ID", "Canonical QBO Row ID",
    "Review ID", "Related Match Ref.", "Related Infinium Row IDs",
    "In Proposed JE",
    "Classification Code", "Evidence Finding", "Candidate Evidence", "Evidence Summary",
]


# One stable, plain-language classification per QuickBooks row, independent of
# the many finer reason codes. The engine writes it; reviewers never edit it.

CLASS_ACCEPTED_MATCH = "ACCEPTED_MATCH"


CLASS_ACCEPTED_MATCH_ID_DISCREPANCY = "ACCEPTED_MATCH_WITH_IDENTIFIER_DISCREPANCY"


CLASS_ACCEPTED_HISTORICAL_MATCH = "ACCEPTED_HISTORICAL_MATCH"


CLASS_TRUE_UNMATCHED = "TRUE_UNMATCHED"


CLASS_AMOUNT_VARIANCE = "AMOUNT_VARIANCE"


CLASS_MULTIPLE_CANDIDATES = "MULTIPLE_CANDIDATES"


CLASS_CONFLICTING_LINKS = "CONFLICTING_IDENTIFIER_LINKS"


CLASS_CONSUMED_EVIDENCE = "ALREADY_REPRESENTED_OR_CONSUMED_EVIDENCE"


CLASS_POSSIBLE_HISTORICAL = "POSSIBLE_HISTORICAL_EVIDENCE"


CLASS_CONFIRMED_DUPLICATE = "CONFIRMED_DUPLICATE"


CLASS_POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"


CLASS_WEAK_EVIDENCE = "WEAK_EVIDENCE_REVIEW"


CLASS_INVALID_AMOUNT = "INVALID_AMOUNT"


CLASS_PO_REUSE = "PO_REUSE"


CLASS_OTHER_REVIEW = "OTHER_REVIEW_HOLD"


HOLD_REASON_CLASS = {
    "REVIEW_HOLD_AMOUNT_VARIANCE": CLASS_AMOUNT_VARIANCE,
    "REVIEW_HOLD_MULTIPLE_CANDIDATES": CLASS_MULTIPLE_CANDIDATES,
    "REVIEW_HOLD_AMBIGUOUS_CANDIDATES": CLASS_MULTIPLE_CANDIDATES,
    "REVIEW_HOLD_EXACT_CANDIDATE_NOT_UNIQUE": CLASS_MULTIPLE_CANDIDATES,
    "REVIEW_HOLD_TYPO_CANDIDATES": CLASS_MULTIPLE_CANDIDATES,
    "REVIEW_HOLD_CONFLICTING_LINKS": CLASS_CONFLICTING_LINKS,
    "REVIEW_HOLD_PO_ALREADY_REPRESENTED": CLASS_CONSUMED_EVIDENCE,
    "REVIEW_HOLD_ALREADY_REPRESENTED": CLASS_CONSUMED_EVIDENCE,
    "REVIEW_HOLD_HISTORICAL_CLEARANCE": CLASS_POSSIBLE_HISTORICAL,
    "REVIEW_HOLD_POTENTIAL_DUPLICATE": CLASS_POSSIBLE_DUPLICATE,
    "REVIEW_HOLD_WEAK_REFERENCE": CLASS_WEAK_EVIDENCE,
    "REVIEW_HOLD_FUZZY_MATCH": CLASS_WEAK_EVIDENCE,
    "REVIEW_HOLD_INVALID_AMOUNT": CLASS_INVALID_AMOUNT,
    "REVIEW_HOLD_CANDIDATE_INVALID_AMOUNT": CLASS_INVALID_AMOUNT,
    "REVIEW_HOLD_PO_REUSE": CLASS_PO_REUSE,
}


MATCH_REF_COLUMN = "Match Ref."


REFERENCED_MATCH_REF_COLUMN = "Referenced Match Ref."


MATCH_TYPE_ONE_TO_ONE = "One-to-One"


MATCH_TYPE_GROUPED = "Grouped"


MATCH_REGISTER_COLUMNS = [
    "Match Ref.", "Match Type", "Record Scope", "Match Basis",
    "QuickBooks Row Count", "Infinium Row Count",
    "QuickBooks Amount", "Infinium Amount", "Amount Difference",
    "QuickBooks Row IDs", "Infinium Row IDs", "Clearance ID",
    "Evidence Summary", "Identifier Discrepancy",
]


_ALREADY_MATCHED_DISPOSITION = "Potential duplicate - referenced Infinium candidate is already matched"
